# Maps file paths to PR labels. Used by auto-label.yml.
ui:
  - changed-files:
      - any-glob-to-any-file: app/src/main/java/com/jonecx/ibex/ui/**

analytics:
  - changed-files:
      - any-glob-to-any-file: app/src/main/java/com/jonecx/ibex/analytics/**

logging:
  - changed-files:
      - any-glob-to-any-file: app/src/main/java/com/jonecx/ibex/logging/**

di:
  - changed-files:
      - any-glob-to-any-file: app/src/main/java/com/jonecx/ibex/di/**

data:
  - changed-files:
      - any-glob-to-any-file: app/src/main/java/com/jonecx/ibex/data/**

tests:
  - changed-files:
      - any-glob-to-any-file:
          - app/src/test/**
          - app/src/androidTest/**
          - app/src/testFixtures/**

screenshot-tests:
  - changed-files:
      - any-glob-to-any-file:
          - app/src/screenshotTest/**
          - app/src/screenshotTestDebug/**

ci:
  - changed-files:
      - any-glob-to-any-file: .github/**

gradle:
  - changed-files:
      - any-glob-to-any-file:
          - '*.gradle.kts'
          - 'app/*.gradle.kts'
          - gradle/**
